#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BACKEND_DIR="$(dirname "$SCRIPT_DIR")"

cd "$BACKEND_DIR"

# Set PYTHONPATH so alembic can import app.models
export PYTHONPATH="${PYTHONPATH:-}:$BACKEND_DIR"

# Default message
MESSAGE="${1:-autogenerated migration}"

echo "🔧 Generating migration: $MESSAGE"
alembic revision --autogenerate -m "$MESSAGE"

echo "✅ Migration created. Review the file in migrations/versions/ before applying."
